USE equippers_manila;

-- Predefined admin account (password: eqprs_mnl_2026!)
-- The hash below is generated by bcrypt with 12 rounds
-- It will be inserted by the seed script in server.js on first run
-- This file is for reference only; the actual seeding uses bcrypt at runtime

-- Sample upcoming services
INSERT IGNORE INTO services (title, service_date, service_time) VALUES
('Sunday Service', CURDATE() + INTERVAL (6 - WEEKDAY(CURDATE())) DAY, '8:30 AM'),
('Sunday Service', CURDATE() + INTERVAL (6 - WEEKDAY(CURDATE())) DAY, '10:30 AM'),
('Sunday Service', CURDATE() + INTERVAL (13 - WEEKDAY(CURDATE())) DAY, '8:30 AM'),
('Sunday Service', CURDATE() + INTERVAL (13 - WEEKDAY(CURDATE())) DAY, '10:30 AM');
